name: lmdb_explorer
description: "A Flutter LMDB explorer"
publish_to: "none"

version: 1.3.0

environment:
  sdk: ^3.10.0

dependencies:
  flutter:
    sdk: flutter

  dart_lmdb: ^0.9.12
  cupertino_icons: ^1.0.8
  flutter_bloc: ^9.1.1
  file_picker: ^10.3.10
  equatable: ^2.0.8
  flat_buffers: ^25.9.23
  window_manager: ^0.5.1
  shared_preferences: ^2.5.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true
  assets:
    - assets/app_icon.png

# Generate app icons (run: dart run flutter_launcher_icons)
flutter_launcher_icons:
  image_path: assets/app_icon.png
  windows:
    generate: true
    image_path: assets/app_icon.png
    icon_size: 256
